# use Ganache's forked mainnet mode as the default network
networks:
  default: arbitrum-main-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# automatically load the local .env file
dotenv: .env

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.10
    viaIR: True
    optimizer:
      runs: 800
    remappings:
      - "@openzeppelin/=lib/openzeppelin-contracts/"
      - "@ironblocks/firewall-consumer=lib/@ironblocks/firewall-consumer/"
      - "@chainlink/=lib/chainlink/"
      - "v3-core/=lib/v3-core/contracts/"
