# use Ganache's forked mainnet mode as the default network
networks:
  default: arbitrum-main-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# automatically load the local .env file
dotenv: .env

# require OpenZepplin, Uniswap Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.2

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.10
    optimizer:
      runs: 800
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2"
      - "solady/=lib/solady/"
