[fmt]
line_length = 99
tab_width = 4
bracket_spacing = false
quote_style = "double"

[profile.default]
src = "contracts"
test = "tests"
script = "scripts"
out = "forge-out"
libs = ["lib"]
# Defender deployments
# Ref: https://docs.openzeppelin.com/defender/v2/tutorial/deploy
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "forge-out" }]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/",
    "v3-core/=lib/v3-core/contracts/"
]

[fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
